Все лабы
pivovarov-mai/hrennikova pull request #4
Opened 2022-05-16 16:03 UTC by lina-tucha

2022-05-21 14:22 UTC, pivovarov-mai requested changes
Пришлите, пожалуйста, исходник python, а не ноутбука.

2022-05-21 14:26 UTC, lina-tucha commented
> Пришлите, пожалуйста, исходник python, а не ноутбука.

Я все делала в ноутбуке, исходника python нет. Могу продемонстрировать все эти лабы при созвоне во вторник.

2022-05-21 14:28 UTC, pivovarov-mai commented
Я понимаю. Дело в том, что когда вы прикрепляете файл ipynb, то вместо исходного текста программы, который вы видите в ноутбуке, я вижу json-кий файл. Сохраните ноутбуки не как ноутбуки, а как python файлы и добавьте их в свою ветку.

2022-05-21 14:45 UTC, lina-tucha commented
Добавила питоновские файлы и пдф, там графики и прочее

2022-05-21 14:47 UTC, pivovarov-mai commented
Отлично, только вот pdf файлы лучше прикрепите к описанию настоящего запроса.

2022-05-21 14:53 UTC, lina-tucha commented
Они не хотят туда крепиться

2022-05-21 15:04 UTC, pivovarov-mai commented
![Снимок экрана 2022-05-21 в 18 03 52](https://user-images.githubusercontent.com/104323436/169657438-f6e83559-1121-458c-831e-259f397807dd.png)

2022-05-21 15:07 UTC, lina-tucha commented
[NM_lab4.pdf](https://github.com/pivovarov-mai/hrennikova/files/8747838/NM_lab4.pdf)
[ML_lab3.pdf](https://github.com/pivovarov-mai/hrennikova/files/8747840/ML_lab3.pdf)
[NM_lab2.pdf](https://github.com/pivovarov-mai/hrennikova/files/8747841/NM_lab2.pdf)
[NM_lab1.pdf](https://github.com/pivovarov-mai/hrennikova/files/8747842/NM_lab1.pdf)

2022-05-24 14:50 UTC, pivovarov-mai approved these changes

2022-05-24 14:50 UTC, merged